Liveness one shot
matemax/lunasdk pull request #101
Opened 2021-01-19 10:21 UTC by matemax

2021-01-19 10:42 UTC, pep8speaks commented
Hello @matemax! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`lunavl/sdk/detectors/facedetector.py`](https://github.com/matemax/lunasdk/blob/1eab5cb2a58afd65f73d77a187a3f603b0245424/lunavl/sdk/detectors/facedetector.py):

> [Line 17:121](https://github.com/matemax/lunasdk/blob/1eab5cb2a58afd65f73d77a187a3f603b0245424/lunavl/sdk/detectors/facedetector.py#L17): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (177 > 120 characters)

* In the file [`lunavl/sdk/detectors/humandetector.py`](https://github.com/matemax/lunasdk/blob/1eab5cb2a58afd65f73d77a187a3f603b0245424/lunavl/sdk/detectors/humandetector.py):

> [Line 13:121](https://github.com/matemax/lunasdk/blob/1eab5cb2a58afd65f73d77a187a3f603b0245424/lunavl/sdk/detectors/humandetector.py#L13): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (235 > 120 characters)





* In the file [`lunavl/sdk/faceengine/engine.py`](https://github.com/matemax/lunasdk/blob/1eab5cb2a58afd65f73d77a187a3f603b0245424/lunavl/sdk/faceengine/engine.py):

> [Line 298:1](https://github.com/matemax/lunasdk/blob/1eab5cb2a58afd65f73d77a187a3f603b0245424/lunavl/sdk/faceengine/engine.py#L298): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 302:1](https://github.com/matemax/lunasdk/blob/1eab5cb2a58afd65f73d77a187a3f603b0245424/lunavl/sdk/faceengine/engine.py#L302): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 306:87](https://github.com/matemax/lunasdk/blob/1eab5cb2a58afd65f73d77a187a3f603b0245424/lunavl/sdk/faceengine/engine.py#L306): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file







* In the file [`tests/schemas.py`](https://github.com/matemax/lunasdk/blob/1eab5cb2a58afd65f73d77a187a3f603b0245424/tests/schemas.py):

> [Line 103:9](https://github.com/matemax/lunasdk/blob/1eab5cb2a58afd65f73d77a187a3f603b0245424/tests/schemas.py#L103): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent

2021-01-20 08:08 UTC, Zeskbest requested changes

2021-01-20 08:08 UTC, Zeskbest commented on docs/_sources/sdk/face_estimations.rst.txt
> +    A correctness of a liveness prediction are not guarantee for other images source.
```suggestion
    A correctness of a liveness prediction is not guaranteed for other images source.
```

2021-01-20 08:08 UTC, Zeskbest commented on docs/_sources/sdk/face_estimations.rst.txt
> +The estimator (see ILivenessOneShotRGBEstimator in sdk). A method estimates whether a real person or not. Output
```suggestion
The estimator (see ILivenessOneShotRGBEstimator in sdk). The method estimates whether a person is real or not. Output
```

2021-01-20 08:08 UTC, Zeskbest commented on docs/_sources/sdk/face_estimations.rst.txt
> +of confidence in the result of estimation. You can add information about a detection head pose to for to improve
```suggestion
of confidence in the result of estimation. You can add information about a detection head pose to improve
```

2021-01-20 08:08 UTC, Zeskbest commented on docs/_sources/sdk/face_estimations.rst.txt
> +a prediction accuracy. Also function contains face detection constrain checkers (detection size and others), if
```suggestion
a prediction accuracy. Also, the function contains face detection constraint checkers (detection size and others), if
```

2021-01-20 08:08 UTC, Zeskbest commented on lunavl/sdk/detectors/facedetector.py
> +        """"""
?

2021-01-20 08:08 UTC, Zeskbest commented on tests/test_livenessv1.py
> +            f"wrong estimation type " f"{type(estimation.prediction)}"
```suggestion
            f"wrong estimation type {type(estimation.prediction)}"
```

2021-01-20 08:08 UTC, Zeskbest commented on lunavl/sdk/faceengine/setting_provider.py
> +            betaMode
```suggestion
            realThreshold
```
?

2021-01-20 11:39 UTC, matemax commented on lunavl/sdk/detectors/facedetector.py
> +        """"""
black.

2021-01-20 12:15 UTC, Zeskbest approved these changes

2021-01-20 12:15 UTC, merged