Face human detector and landmarks estimators
matemax/lunasdk pull request #145
Opened 2022-09-05 12:10 UTC by matemax

2022-09-05 12:10 UTC, pep8speaks commented
Hello @matemax! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:























* In the file [`tests/test_human_detector.py`](https://github.com/matemax/lunasdk/blob/4d6aacb8e120311e65dcc8ea140b5257b2ed7bd4/tests/test_human_detector.py):

> [Line 71:21](https://github.com/matemax/lunasdk/blob/4d6aacb8e120311e65dcc8ea140b5257b2ed7bd4/tests/test_human_detector.py#L71): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 71:21](https://github.com/matemax/lunasdk/blob/4d6aacb8e120311e65dcc8ea140b5257b2ed7bd4/tests/test_human_detector.py#L71): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 71:22](https://github.com/matemax/lunasdk/blob/4d6aacb8e120311e65dcc8ea140b5257b2ed7bd4/tests/test_human_detector.py#L71): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 77:21](https://github.com/matemax/lunasdk/blob/4d6aacb8e120311e65dcc8ea140b5257b2ed7bd4/tests/test_human_detector.py#L77): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 77:21](https://github.com/matemax/lunasdk/blob/4d6aacb8e120311e65dcc8ea140b5257b2ed7bd4/tests/test_human_detector.py#L77): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 77:22](https://github.com/matemax/lunasdk/blob/4d6aacb8e120311e65dcc8ea140b5257b2ed7bd4/tests/test_human_detector.py#L77): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

2022-09-07 16:42 UTC, ddc67cd requested changes

2022-09-07 16:42 UTC, ddc67cd commented on lunavl/sdk/estimators/face_estimators/landmarks.py
> +    ) -> Union[Landmarks5, Landmarks68, AsyncTask[Landmarks5], AsyncTask[Landmarks68]]:
Using both overload and unions makes no sense

2022-09-07 16:42 UTC, ddc67cd commented on lunavl/sdk/detectors/humandetector.py
> +) -> Union[List[List[HumanDetection]]]:
```suggestion
) -> HumanDetectResult:
```

2022-09-07 16:42 UTC, ddc67cd commented on lunavl/sdk/faceengine/setting_provider.py
> +        return self.getValue("faceThreshold")
Smells like a boilerplate.

2022-09-07 16:42 UTC, ddc67cd commented on lunavl/sdk/detectors/humandetector.py
> +    def asDict(self) -> Dict[str, Any]:
Not about object behavior, but rather representation. Client's should depend on the public attributes, not the dictionary. And its kinda hard to inherit from a such method.

2022-09-08 07:47 UTC, matemax commented on lunavl/sdk/faceengine/setting_provider.py
> +        return self.getValue("faceThreshold")
create issue

2022-09-08 08:18 UTC, matemax commented on lunavl/sdk/faceengine/setting_provider.py
> +        return self.getValue("faceThreshold")
https://github.com/matemax/lunasdk/issues/146

2022-09-08 08:30 UTC, matemax commented on lunavl/sdk/estimators/face_estimators/landmarks.py
> +    ) -> Union[Landmarks5, Landmarks68, AsyncTask[Landmarks5], AsyncTask[Landmarks68]]:
remove

2022-09-08 09:40 UTC, ddc67cd approved these changes

2022-09-08 09:40 UTC, merged