upd redetect exception context
matemax/lunasdk pull request #94
Opened 2020-10-27 07:47 UTC by gluhar2006

2020-10-27 10:25 UTC, matemax commented on lunavl/sdk/detectors/facedetector.py
> +        assertError(mainError, errors)
+ test

2020-10-28 08:48 UTC, gluhar2006 commented on lunavl/sdk/detectors/facedetector.py
> +        assertError(mainError, errors)
added

2020-10-28 09:37 UTC, gluhar2006 commented on lunavl/sdk/detectors/humandetector.py
> +                    errors.append(exc.error)
.

2020-10-28 14:40 UTC, matemax approved these changes

2020-10-28 14:40 UTC, matemax commented on lunavl/sdk/detectors/humandetector.py
> +                    isDetectionSuccess = False
I think that one image one error
```python
for bBox in image.bBoxes:
    try:
        detection = self.redetectOne(image.image, bBox=bBox)
        imageRes.append(detection)
    except LunaSDKException as exc:
         errors.append(exc.error)
         break
    else:
         errors.append(Error.Succes)
else:
    res.append(imageRes)

2020-10-28 14:40 UTC, matemax commented on lunavl/sdk/errors/exceptions.py
> +        if isinstance(error, FSDKErrorValueBool):
what?

2020-10-29 18:16 UTC, pep8speaks commented
Hello @gluhar2006! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`lunavl/sdk/detectors/humandetector.py`](https://github.com/matemax/lunasdk/blob/1b9cc2af347ee59e8dd56c991c5c2602081d38e9/lunavl/sdk/detectors/humandetector.py):

> [Line 143:121](https://github.com/matemax/lunasdk/blob/1b9cc2af347ee59e8dd56c991c5c2602081d38e9/lunavl/sdk/detectors/humandetector.py#L143): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

2020-10-30 12:18 UTC, gluhar2006 commented on lunavl/sdk/detectors/humandetector.py
> +                    isDetectionSuccess = False
updated

2020-10-30 12:18 UTC, gluhar2006 commented on lunavl/sdk/errors/exceptions.py
> +        if isinstance(error, FSDKErrorValueBool):
removed

2020-11-02 10:28 UTC, Zeskbest requested changes

2020-11-02 10:28 UTC, Zeskbest commented on lunavl/sdk/detectors/humandetector.py
> +            [imgs[0]], [detectAreas[0]], 1, self._getDetectionType(detectLandmarks)
i o not understand, what is `1` here

make it keyworded

2020-11-02 10:28 UTC, Zeskbest commented on lunavl/sdk/detectors/humandetector.py
> +            raise LunaSDKException(LunaVLError.BatchedInternalError, errors)
there is no batching. Why `LunaVLError.BatchedInternalError` is raised?

2020-11-02 10:28 UTC, Zeskbest commented on lunavl/sdk/errors/exceptions.py
> +        context: list with LunaSdkExceptions
This is typing, not a comment

2020-11-02 10:28 UTC, Zeskbest commented on tests/base.py
> +        assert expectedErrorWithoutDesc.description == receivedError.detail
expectedErrorWithoutDesc.description  - is it empty? rename pls

2020-11-02 10:28 UTC, Zeskbest commented on lunavl/sdk/estimators/estimators_utils/extractor_utils.py
> +        """Extract descriptor without batching and collect errors"""
add raises field

2020-11-02 10:28 UTC, Zeskbest commented on tests/test_estimate_descriptor.py
>      @unittest.skip("dont do it FSDK-2186")
unskip pls

2020-11-02 10:28 UTC, Zeskbest commented on tests/test_estimate_descriptor.py
> +            with self.subTest(type=case.type):
one subtest pls

2020-11-02 10:28 UTC, Zeskbest commented on tests/test_facedetector.py
>  from tests.detect_test_class import (
why splitted?

2020-11-02 10:28 UTC, Zeskbest commented on tests/test_facedetector.py
> +        Test batch detection with success and error using FACE_DET_V3 (only need to check errors)
why FACE_DET_V3 only?

2020-11-02 10:28 UTC, Zeskbest commented on lunavl/sdk/estimators/face_estimators/basic_attributes.py
> +                    errors.append(LunaVLError.fromSDKError(error))
errorOne

2020-11-02 10:49 UTC, Zeskbest commented on lunavl/sdk/estimators/estimators_utils/extractor_utils.py
> +        raise LunaSDKException(LunaVLError.BatchedInternalError, errors)
just return errors here

2020-11-02 12:16 UTC, gluhar2006 commented on lunavl/sdk/detectors/humandetector.py
> +            [imgs[0]], [detectAreas[0]], 1, self._getDetectionType(detectLandmarks)
unfortenatuly I cannot; comment added

2020-11-02 12:16 UTC, gluhar2006 commented on lunavl/sdk/errors/exceptions.py
> +        context: list with LunaSdkExceptions
upd

2020-11-02 12:16 UTC, gluhar2006 commented on tests/base.py
> +        assert expectedErrorWithoutDesc.description == receivedError.detail
renamed

2020-11-02 12:16 UTC, gluhar2006 commented on lunavl/sdk/estimators/estimators_utils/extractor_utils.py
> +        """Extract descriptor without batching and collect errors"""
raising moved

2020-11-02 12:16 UTC, gluhar2006 commented on tests/test_estimate_descriptor.py
>      @unittest.skip("dont do it FSDK-2186")
ok

2020-11-02 12:16 UTC, gluhar2006 commented on tests/test_estimate_descriptor.py
> +            with self.subTest(type=case.type):
ok

2020-11-02 12:16 UTC, gluhar2006 commented on tests/test_facedetector.py
>  from tests.detect_test_class import (
pycharm

2020-11-02 12:16 UTC, gluhar2006 commented on tests/test_facedetector.py
> +        Test batch detection with success and error using FACE_DET_V3 (only need to check errors)
update description

2020-11-02 12:16 UTC, gluhar2006 commented on lunavl/sdk/estimators/face_estimators/basic_attributes.py
> +                    errors.append(LunaVLError.fromSDKError(error))
fixed

2020-11-02 12:16 UTC, gluhar2006 commented on lunavl/sdk/estimators/estimators_utils/extractor_utils.py
> +        raise LunaSDKException(LunaVLError.BatchedInternalError, errors)
noway

2020-11-02 12:52 UTC, Zeskbest commented on tests/test_facedetector.py
> +        Test batch detection with success and error using FACE_DET_V3 (there is not error with other detector)
```suggestion
        Test batch detection with success and error using FACE_DET_V3 (there is no error with other detector)
```

2020-11-02 13:21 UTC, Zeskbest approved these changes

2020-11-02 13:21 UTC, merged